[package]
name = "bila"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.18.0"
macroquad = "0.3.9"

[profile.dev.package."*"]
opt-level = 1
